// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VirtualPlanetarium.CodeFirst;

#nullable disable

namespace VirtualPlanetarium.CodeFirst.Migrations
{
    [DbContext(typeof(PlanetariumDbContext))]
    [Migration("20251227182128_AddOwnedEntityAddress")]
    partial class AddOwnedEntityAddress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VirtualPlanetarium.CodeFirst.Models.CelestialObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateDiscovered")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Declination")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("RightAscension")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("SpectralClass")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("TypeId");

                    b.ToTable("CelestialObjects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The star at the center of the Solar System",
                            GroupId = 1,
                            Name = "Sun",
                            Tags = "",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Our home planet",
                            GroupId = 1,
                            Name = "Earth",
                            Tags = "",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Nearest major galaxy",
                            GroupId = 2,
                            Name = "Andromeda",
                            Tags = "",
                            TypeId = 3
                        });
                });

            modelBuilder.Entity("VirtualPlanetarium.CodeFirst.Models.ObjectGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ObjectGroups", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Solar System"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Local Group"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Deep Space"
                        });
                });

            modelBuilder.Entity("VirtualPlanetarium.CodeFirst.Models.ObjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ObjectTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Star"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Planet"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Galaxy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Nebula"
                        });
                });

            modelBuilder.Entity("VirtualPlanetarium.CodeFirst.Models.Observation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CelestialObjectId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ObservationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CelestialObjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Observations", (string)null);
                });

            modelBuilder.Entity("VirtualPlanetarium.CodeFirst.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CelestialObjectId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CelestialObjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews", null, t =>
                        {
                            t.HasCheckConstraint("CK_Reviews_Rating", "[Rating] >= 1 AND [Rating] <= 5");
                        });
                });

            modelBuilder.Entity("VirtualPlanetarium.CodeFirst.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ObsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@planetarium.com",
                            ObsCount = 0,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("VirtualPlanetarium.CodeFirst.Models.CelestialObject", b =>
                {
                    b.HasOne("VirtualPlanetarium.CodeFirst.Models.ObjectGroup", "Group")
                        .WithMany("CelestialObjects")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VirtualPlanetarium.CodeFirst.Models.ObjectType", "Type")
                        .WithMany("CelestialObjects")
                        .HasForeignKey("TypeId")
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("VirtualPlanetarium.CodeFirst.Models.Observation", b =>
                {
                    b.HasOne("VirtualPlanetarium.CodeFirst.Models.CelestialObject", "CelestialObject")
                        .WithMany("Observations")
                        .HasForeignKey("CelestialObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualPlanetarium.CodeFirst.Models.User", "User")
                        .WithMany("Observations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CelestialObject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VirtualPlanetarium.CodeFirst.Models.Review", b =>
                {
                    b.HasOne("VirtualPlanetarium.CodeFirst.Models.CelestialObject", "CelestialObject")
                        .WithMany()
                        .HasForeignKey("CelestialObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualPlanetarium.CodeFirst.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CelestialObject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VirtualPlanetarium.CodeFirst.Models.User", b =>
                {
                    b.OwnsOne("VirtualPlanetarium.CodeFirst.Models.Address", "Address", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Country");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("ZipCode");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("VirtualPlanetarium.CodeFirst.Models.CelestialObject", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("VirtualPlanetarium.CodeFirst.Models.ObjectGroup", b =>
                {
                    b.Navigation("CelestialObjects");
                });

            modelBuilder.Entity("VirtualPlanetarium.CodeFirst.Models.ObjectType", b =>
                {
                    b.Navigation("CelestialObjects");
                });

            modelBuilder.Entity("VirtualPlanetarium.CodeFirst.Models.User", b =>
                {
                    b.Navigation("Observations");
                });
#pragma warning restore 612, 618
        }
    }
}
